# Generated by Django 6.0.5 on 2026-05-09 15:40

import django.db.models.deletion
from django.db import migrations, models


def seed_subject_data(apps, schema_editor):
    Department = apps.get_model("dashboard", "Department")
    Subject = apps.get_model("dashboard", "Subject")
    Teacher = apps.get_model("dashboard", "Teacher")

    subject_names = (
        Teacher.objects.exclude(subject="")
        .values_list("subject", "department__name", "classes")
        .distinct()
        .order_by("subject")
    )
    for index, row in enumerate(subject_names, start=1):
        name, department_name, classes = row
        department = None
        if department_name:
            department = Department.objects.filter(name=department_name).first()
        Subject.objects.update_or_create(
            code=f"SUB{index:03}",
            defaults={
                "name": name,
                "department": department,
                "teachers": Teacher.objects.filter(subject=name).count(),
                "classes": classes or "Not assigned",
                "weekly_hours": 4,
                "status": "Active",
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('teachers', models.PositiveIntegerField(default=0)),
                ('classes', models.CharField(default='Not assigned', max_length=120)),
                ('weekly_hours', models.PositiveIntegerField(default=4)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='dashboard.department')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.RunPython(seed_subject_data, migrations.RunPython.noop),
    ]
